export const REQUEST_UPDATE_TRIP_STATUS = 'REQUEST_UPDATE_TRIP_STATUS';
export const UPDATE_TRIP_STATUS_SUCCESS = 'UPDATE_TRIP_STATUS_SUCCESS';
export const UPDATE_TRIP_STATUS_FAILURE = 'UPDATE_TRIP_STATUS_FAILURE';
