// CREATE AN ACCOMMODATIONS
export const CREATE_ACCOMMODATION_REQUEST = 'CREATE_ACCOMMODATION_REQUEST';
export const CREATE_ACCOMMODATION_SUCCESS = 'CREATE_ACCOMMODATION_SUCCESS';
export const CREATE_ACCOMMODATION_FAILURE = 'CREATE_ACCOMMODATION_FAILURE';

// DELETE AN ACCOMMODATION
export const DELETE_ACCOMMODATION_START = 'DELETE_ACCOMMODATION_START';
export const DELETE_ACCOMMODATION_SUCCESS = 'DELETE_ACCOMMODATION_SUCCESS';
export const DELETE_ACCOMMODATION_FAILURE = 'DELETE_ACCOMMODATION_FAILURE';

// UPDATE AN ACCOMMODATION
export const EDIT_ACCOMMODATION_START = 'EDIT_ACCOMMODATION_START';
export const EDIT_ACCOMMODATION_SUCCESS = 'EDIT_ACCOMMODATION_SUCCESS';
export const EDIT_ACCOMMODATION_FAILURE = 'EDIT_ACCOMMODATION_FAILURE';

// Retrieve location

export const FETCH_LOCATIONS_START = 'FETCH_LOCATIONS_START';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';
