export const REQUEST_TRIP = 'REQUEST_TRIP';
export const REQUEST_TRIP_SUCCESS = 'REQUEST_TRIP_SUCCESS';
export const REQUEST_TRIP_ERROR = 'REQUEST_TRIP_ERROR';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS';
export const UPDATE_REQUEST_ERROR = 'UPDATE_REQUEST_ERROR';
export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST';
export const FETCH_LOCATION_FAIL = 'FETCH_LOCATION_FAIL';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_ACCOMMODATION_REQUEST = 'FETCH_ACCOMMODATION_REQUEST';
export const FETCH_ACCOMMODATION_FAIL = 'FETCH_ACCOMMODATION_FAIL';
export const FETCH_ACCOMMODATION_SUCCESS = 'FETCH_ACCOMMODATION_SUCCESS';

export const SET_LOADING = 'SET_LOADING';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
