export const SET_LOADING = 'SET_LOADING';

// Login
export const SET_AUTH_PENDING = 'SET_AUTH_PENDING';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';

// For trip requests
export const FETCH_REQUESTS_PENDING = 'FETCH_REQUESTS_PENDING';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';

// For getting current logged in user
export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING';
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';

// for social login
export const OAUTH_SUCCESS = 'OAUTH_SUCCESS';
export const OAUTH_FAILURE = 'OAUTH_FAILURE';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
// for fetching an accommodation

export const FETCH_ACCOMMODATION_PENDING = 'FETCH_ACCOMMODATION_PENDING';
export const FETCH_ACCOMMODATION_SUCCESS = 'FETCH_ACCOMMODATION_SUCCESS';
export const FETCH_ACCOMMODATION_FAILURE = 'FETCH_ACCOMMODATION_FAILURE';

// for fetching singleAccommodation
export const FETCH_SINGLE_ACCOMMODATION_PENDING = 'FETCH_SINGLE_ACCOMMODATION_PENDING';
export const FETCH_SINGLE_ACCOMMODATION_SUCCESS = 'FETCH_SINGLE_ACCOMMODATION_SUCCESS';
export const FETCH_SINGLE_ACCOMMODATION_FAILURE = 'FETCH_SINGLE_ACCOMMODATION_FAILURE';

// Requester dashboard
export const FETCH_REQUESTER_DASHBOARD_PENDING = 'FETCH_REQUESTER_DASHBOARD_PENDING';
export const FETCH_REQUESTER_DASHBOARD_ERROR = 'FETCH_REQUESTER_DASHBOARD_ERROR';
export const FETCH_REQUESTER_DASHBOARD_SUCCESS = 'FETCH_REQUESTER_DASHBOARD_SUCCESS';

// Popular accommodations
export const FETCH_POPULAR_ACCOMMODATIONS_PENDING = 'FETCH_POPULAR_ACCOMMODATIONS_PENDING';
export const FETCH_POPULAR_ACCOMMODATIONS_ERROR = 'FETCH_POPULAR_ACCOMMODATIONS_ERROR';
export const FETCH_POPULAR_ACCOMMODATIONS_SUCCESS = 'FETCH_POPULAR_ACCOMMODATIONS_SUCCESS';

// Latest trips
export const FETCH_LATEST_TRIPS_PENDING = 'FETCH_LATEST_TRIPS_PENDING';
export const FETCH_LATEST_TRIPS_ERROR = 'FETCH_LATEST_TRIPS_ERROR';
export const FETCH_LATEST_TRIPS_SUCCESS = 'FETCH_LATEST_TRIPS_SUCCESS';
