export const SET_LOADING = 'SET_LOADING';

// Login
export const SET_AUTH_PENDING = 'SET_AUTH_PENDING';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// For trip requests
export const FETCH_REQUESTS_PENDING = 'FETCH_REQUESTS_PENDING';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';

// For getting current logged in user
export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING';
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';

// for social login
export const OAUTH_SUCCESS = 'OAUTH_SUCCESS';
export const OAUTH_FAILURE = 'OAUTH_FAILURE';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';

// for fetching an accommodation
export const FETCH_ACCOMMODATION_PENDING = 'FETCH_ACCOMMODATION_PENDING';
export const FETCH_ACCOMMODATION_SUCCESS = 'FETCH_ACCOMMODATION_SUCCESS';
export const FETCH_ACCOMMODATION_FAILURE = 'FETCH_ACCOMMODATION_FAILURE';

// for fetching singleAccommodation
export const FETCH_SINGLE_ACCOMMODATION_PENDING = 'FETCH_SINGLE_ACCOMMODATION_PENDING';
export const FETCH_SINGLE_ACCOMMODATION_SUCCESS = 'FETCH_SINGLE_ACCOMMODATION_SUCCESS';
export const FETCH_SINGLE_ACCOMMODATION_FAILURE = 'FETCH_SINGLE_ACCOMMODATION_FAILURE';

// room boking
export const ROOM_BOOKING_PENDING = 'ROOM_BOOKING_PENDING';
export const ROOM_BOOKING_SUCCESS = 'ROOM_BOOKING_SUCCESS';
export const ROOM_BOOKING_FAILURE = 'ROOM_BOOKING_FAILURE';

// for all notifications
export const FETCH_NOTIFICATIONS_PENDING = 'FETCH_NOTIFICATIONS_PENDING';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';

export const READ_NOTIFICATION_PENDING = 'READ_NOTIFICATION_PENDING';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_ERROR = 'READ_NOTIFICATION_ERROR';
export const READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS';

export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
